#!/bin/sh

# if test getarch_cmd -ot getarch.c; then
#     rm -f getarch_cmd
# fi

if test ! -x getarch_cmd; then
    rm -f getarch_cmd
    $2 -w $3 $4 -o getarch_cmd getarch.c cpuid.S > /dev/null
    if test ! -x getarch_cmd; then
	$2 $3 $4 -o getarch_cmd getarch.c cpuid.S > /dev/null
    fi
fi

./getarch_cmd $1
